// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekbnwbetuztzskdxdwgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrYm53YmV0dXp0enNrZHhkd2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwNzQwNTcsImV4cCI6MjA2NTY1MDA1N30.P2udY7YAxnu7vaQ2F7efeJ9SYkBQ8JGjp9dihELO3XU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);